services:
  server:
    build: .
    command: pnpm run server
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"

  demo:
    build: .
    command: pnpm run demo
    environment:
      VITE_OCULUS_SERVER_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - server
